apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: {{ .Values.ports.protocol}}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}
  clusterIP: None
